--- #YAML:1.0
name:               Lingua-RU-Inflect
version:            0.04
abstract:           Lingua::RU::Inflect - Inflect russian names
author:
    - Alexander Sapozhnikov <shoorick@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::MoreUtils:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
